"""
LiveKit Setup Helper
This script helps you set up LiveKit credentials for real-time avatar sessions
"""
import os
import sys

print("LiveKit Setup Helper")
print("=" * 60)
print("\nTo use Beyond Presence real-time avatars, you need LiveKit.")
print("\nOption 1: LiveKit Cloud (Recommended for getting started)")
print("  1. Sign up at: https://cloud.livekit.io")
print("  2. Create a new project")
print("  3. Get your credentials from the project settings:")
print("     - LiveKit URL (e.g., wss://your-project.livekit.cloud)")
print("     - API Key")
print("     - API Secret")
print("\nOption 2: Self-hosted LiveKit")
print("  1. Follow guide: https://docs.livekit.io/home/self-hosting/deployment/")
print("  2. Get your server URL and credentials")
print("\n" + "=" * 60)

# Interactive setup
print("\nLet's configure your LiveKit credentials:")
print("(Press Enter to skip any field)\n")

livekit_url = input("LiveKit URL (e.g., wss://your-project.livekit.cloud): ").strip()
livekit_api_key = input("LiveKit API Key: ").strip()
livekit_api_secret = input("LiveKit API Secret: ").strip()

if livekit_url and livekit_api_key and livekit_api_secret:
    # Create .env file
    env_content = f"""# Beyond Presence & LiveKit Configuration
# Generated by setup_livekit.py

# Beyond Presence API
BEY_API_KEY=sk-WqWFLJ7Jf_AWCFTgH-L_Pg11jifisvwC4IJaQ2v41SE
AVATAR_ID=b63ba4e6-d346-45d0-ad28-5ddffaac0bd0_v2

# LiveKit Configuration
LIVEKIT_URL={livekit_url}
LIVEKIT_API_KEY={livekit_api_key}
LIVEKIT_API_SECRET={livekit_api_secret}

# Optional: OpenAI (for STT/LLM/TTS in voice assistant)
# OPENAI_API_KEY=your-openai-key-here
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✓ Configuration saved to .env file")
    print("\nTo use these credentials:")
    print("  Python: pip install python-dotenv")
    print("  Node.js: npm install dotenv")
    print("\nNext steps:")
    print("  1. Test your setup with: python test_livekit.py")
    print("  2. Run the full example: python python_example.py dev")
else:
    print("\n⚠ No credentials provided. You can manually create a .env file:")
    print("\nExample .env file:")
    print("-" * 60)
    print("""BEY_API_KEY=sk-WqWFLJ7Jf_AWCFTgH-L_Pg11jifisvwC4IJaQ2v41SE
AVATAR_ID=b63ba4e6-d346-45d0-ad28-5ddffaac0bd0_v2
LIVEKIT_URL=wss://your-project.livekit.cloud
LIVEKIT_API_KEY=your-livekit-key
LIVEKIT_API_SECRET=your-livekit-secret
OPENAI_API_KEY=your-openai-key-here""")
    print("-" * 60)
